import type { Metadata } from "next";
import { Geist, Geist_Mono, Jaini, Allura } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import PageProgress from "./components/PageProgress";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const gillianReg = localFont({
  src: "../public/fonts/Gillian Regular.otf",
  variable: "--font-gillian-regular",
  display: "swap",
});

const jaini = Jaini({
  variable: "--font-jaini",
  display: "swap",
  weight: "400",
});

const allura = Allura({
  variable: "--font-allura",
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Wedding Invitation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${gillianReg.variable} ${jaini.variable} ${allura.variable} antialiased relative`}
        suppressHydrationWarning={true}
      >
        <PageProgress />
        {children}
      </body>
    </html>
  );
}
